<?php
$z[0]=Array("arcurl","",31,46);
$z[1]=Array("title","",55,69);
$z[2]=Array("litpic","",81,96);
$z[3]=Array("title","",104,118);
$z[4]=Array("title","",127,141);
$z[5]=Array("arcurl","",204,219);
$z[6]=Array("title","",228,242);
$z[7]=Array("title","",244,258);
$z[8]=Array("description","",282,332);
$z[8][4]['function']="cn_substr(@me,240)";
$z[9]=Array("arcurl","",363,378);
$z[10]=Array("title","",387,401);

?>