<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a>|",90,206);
$z[0][4]['type']="top";
$z[1]=Array("global","",294,320);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",329,355);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",414,440);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",458,482);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",522,543);
$z[5][4]['name']="cfg_dh";
$z[6]=Array("global","",570,591);
$z[6][4]['name']="cfg_dz";

?>