<?php
$z[0]=Array("global","",56,77);
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",92,202);
$z[1][4]['typeid']="1";
$z[2]=Array("type"," <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",205,315);
$z[2][4]['typeid']="7";
$z[3]=Array("global","",383,409);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",449,475);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",502,523);
$z[5][4]['name']="cfg_dh";
$z[6]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a>",736,851);
$z[6][4]['type']="top";

?>