<?php
$z[0]=Array("field","",141,163);
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n        <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n        ",178,320);
$z[1][4]['type']="son";
$z[2]=Array("arclist","\r\n    <div class=\"tcp\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:litpic/]\"  alt=\"[field:title/]\" title=\"[field:title/]\"/>\r\n      <p>[field:title/]</p>\r\n      </a> </div>\r\n    ",428,673);
$z[2][4]['row']="3";
$z[2][4]['typeid']="2";
$z[3]=Array("global","",866,887);
$z[3][4]['name']="cfg_dh";
$z[4]=Array("global","",955,976);
$z[4][4]['name']="cfg_dz";

?>